-- DEBES ACTIVAR EL INICIO DE SESION DE MODO MIXTO SI NO ESTA ACTIVO
IF NOT EXISTS (SELECT 1 FROM sys.syslogins WHERE name = 'SCM')
BEGIN
    USE master;
    CREATE LOGIN SCM WITH PASSWORD = '123';
    USE SCM;
    CREATE USER SCM FOR LOGIN SCM;
    GRANT SELECT, INSERT, UPDATE, DELETE TO SCM;
END

USE SCM;
-- Otorgar permisos de SELECT, UPDATE, DELETE al usuario SCM
GRANT SELECT, UPDATE, DELETE TO SCM;
-- Otorgar permiso de ejecución de procedimientos almacenados al usuario SCM
GRANT EXECUTE TO SCM;
ALTER LOGIN SCM WITH PASSWORD = '123', CHECK_EXPIRATION = OFF;

--CORREGIR LA COLUMNA  EstadoActual INT NULL, EN CD_CAMBIOS AHORA = 9, LUEGO = 7
